"""
TITAN 3.0 - Core Strategy Module
Implements the base strategy architecture for automated trading strategies.
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from datetime import datetime
import pandas as pd
import numpy as np
from enum import Enum


class SignalType(Enum):
    """Types of trading signals."""
    LONG = "LONG"
    SHORT = "SHORT"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"
    HOLD = "HOLD"


class Timeframe(Enum):
    """Supported timeframes."""
    MINUTE_1 = "1m"
    MINUTE_5 = "5m"
    MINUTE_15 = "15m"
    MINUTE_30 = "30m"
    HOUR_1 = "1h"
    HOUR_4 = "4h"
    DAY = "1d"
    WEEK = "1w"


@dataclass
class TradeSignal:
    """Represents a trading signal generated by a strategy."""
    signal_type: SignalType
    timestamp: datetime
    price: float
    confidence: float  # 0.0 to 1.0
    strategy_id: str
    strategy_name: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict:
        return {
            'signal_type': self.signal_type.value,
            'timestamp': self.timestamp.isoformat(),
            'price': self.price,
            'confidence': self.confidence,
            'strategy_id': self.strategy_id,
            'strategy_name': self.strategy_name,
            'metadata': self.metadata
        }


@dataclass
class Position:
    """Represents an open position."""
    symbol: str
    entry_price: float
    quantity: float
    side: SignalType
    entry_time: datetime
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    
    def update_price(self, price: float):
        """Update current price and calculate unrealized PnL."""
        self.current_price = price
        if self.side == SignalType.LONG:
            self.unrealized_pnl = (price - self.entry_price) * self.quantity
        else:
            self.unrealized_pnl = (self.entry_price - price) * self.quantity


@dataclass
class StrategyPerformance:
    """Performance metrics for a strategy."""
    total_return: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    calmar_ratio: float = 0.0
    sortino_ratio: float = 0.0


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies in TITAN 3.0.
    All custom strategies must inherit from this class.
    """
    
    def __init__(self, 
                 strategy_id: str,
                 name: str,
                 description: str,
                 timeframe: Timeframe = Timeframe.HOUR_1,
                 symbols: List[str] = None,
                 parameters: Dict[str, Any] = None):
        self.strategy_id = strategy_id
        self.name = name
        self.description = description
        self.timeframe = timeframe
        self.symbols = symbols or []
        self.parameters = parameters or {}
        self.is_active = False
        self.created_at = datetime.now()
        self.last_updated = datetime.now()
        
    @abstractmethod
    def generate_signal(self, 
                       data: pd.DataFrame,
                       features: Dict[str, pd.Series],
                       regime: str,
                       current_position: Optional[Position] = None) -> Optional[TradeSignal]:
        """
        Generate a trading signal based on input data.
        
        Args:
            data: OHLCV dataframe with columns ['open', 'high', 'low', 'close', 'volume']
            features: Dictionary of computed features/indicators
            regime: Current market regime ('bull', 'bear', 'sideways', 'volatile')
            current_position: Current open position if any
            
        Returns:
            TradeSignal if a signal is generated, None otherwise
        """
        pass
    
    @abstractmethod
    def calculate_position_size(self, 
                               signal: TradeSignal,
                               account_balance: float,
                               risk_per_trade: float = 0.02,
                               volatility: float = 0.0) -> float:
        """
        Calculate optimal position size based on risk management rules.
        
        Args:
            signal: The trade signal
            account_balance: Current account balance
            risk_per_trade: Fraction of account to risk per trade (default 2%)
            volatility: Current asset volatility
            
        Returns:
            Position size in units
        """
        pass
    
    def validate_parameters(self) -> bool:
        """Validate strategy parameters before activation."""
        required_params = getattr(self, 'required_parameters', [])
        for param in required_params:
            if param not in self.parameters:
                raise ValueError(f"Missing required parameter: {param}")
        return True
    
    def activate(self):
        """Activate the strategy for signal generation."""
        self.validate_parameters()
        self.is_active = True
        self.last_updated = datetime.now()
        
    def deactivate(self):
        """Deactivate the strategy."""
        self.is_active = False
        self.last_updated = datetime.now()
    
    def get_metadata(self) -> Dict[str, Any]:
        """Get strategy metadata."""
        return {
            'strategy_id': self.strategy_id,
            'name': self.name,
            'description': self.description,
            'timeframe': self.timeframe.value,
            'symbols': self.symbols,
            'parameters': self.parameters,
            'is_active': self.is_active,
            'created_at': self.created_at.isoformat(),
            'last_updated': self.last_updated.isoformat()
        }
    
    def __repr__(self):
        return f"{self.__class__.__name__}(id={self.strategy_id}, name={self.name})"


class MomentumStrategy(BaseStrategy):
    """
    Example implementation: Momentum-based strategy.
    Buys when momentum is strong and positive, sells when negative.
    """
    
    def __init__(self, 
                 strategy_id: str = "momentum_001",
                 name: str = "Momentum Breakout",
                 description: str = "Captures momentum breakouts using RSI and MACD",
                 timeframe: Timeframe = Timeframe.HOUR_1,
                 symbols: List[str] = None,
                 parameters: Dict[str, Any] = None):
        
        default_params = {
            'rsi_period': 14,
            'rsi_overbought': 70,
            'rsi_oversold': 30,
            'macd_fast': 12,
            'macd_slow': 26,
            'macd_signal': 9,
            'min_volume_ratio': 1.5
        }
        
        super().__init__(
            strategy_id=strategy_id,
            name=name,
            description=description,
            timeframe=timeframe,
            symbols=symbols,
            parameters={**default_params, **(parameters or {})}
        )
        
        self.required_parameters = ['rsi_period', 'rsi_overbought', 'rsi_oversold']
    
    def generate_signal(self, 
                       data: pd.DataFrame,
                       features: Dict[str, pd.Series],
                       regime: str,
                       current_position: Optional[Position] = None) -> Optional[TradeSignal]:
        
        if not self.is_active or len(data) < 2:
            return None
        
        latest_close = data['close'].iloc[-1]
        latest_time = data.index[-1]
        
        # Get features
        rsi = features.get('rsi')
        macd = features.get('macd')
        macd_signal = features.get('macd_signal')
        volume_ratio = features.get('volume_ratio')
        
        if rsi is None or macd is None:
            return None
        
        latest_rsi = rsi.iloc[-1] if hasattr(rsi, 'iloc') else rsi[-1]
        latest_macd = macd.iloc[-1] if hasattr(macd, 'iloc') else macd[-1]
        latest_macd_signal_line = macd_signal.iloc[-1] if hasattr(macd_signal, 'iloc') else macd_signal[-1]
        latest_vol_ratio = volume_ratio.iloc[-1] if volume_ratio is not None and hasattr(volume_ratio, 'iloc') else 1.0
        
        # Avoid trading in sideways regime
        if regime == 'sideways':
            return None
        
        # Check for long signal
        if (latest_rsi < self.parameters['rsi_oversold'] and 
            latest_macd > latest_macd_signal_line and
            latest_vol_ratio >= self.parameters['min_volume_ratio']):
            
            return TradeSignal(
                signal_type=SignalType.LONG,
                timestamp=latest_time,
                price=latest_close,
                confidence=min(0.95, 0.5 + (latest_rsi / 100) * 0.3),
                strategy_id=self.strategy_id,
                strategy_name=self.name,
                metadata={
                    'rsi': latest_rsi,
                    'macd': latest_macd,
                    'regime': regime
                }
            )
        
        # Check for short signal
        elif (latest_rsi > self.parameters['rsi_overbought'] and 
              latest_macd < latest_macd_signal_line and
              latest_vol_ratio >= self.parameters['min_volume_ratio']):
            
            return TradeSignal(
                signal_type=SignalType.SHORT,
                timestamp=latest_time,
                price=latest_close,
                confidence=min(0.95, 0.5 + ((100 - latest_rsi) / 100) * 0.3),
                strategy_id=self.strategy_id,
                strategy_name=self.name,
                metadata={
                    'rsi': latest_rsi,
                    'macd': latest_macd,
                    'regime': regime
                }
            )
        
        # Close positions if momentum fades
        if current_position:
            if current_position.side == SignalType.LONG and latest_rsi > 60:
                return TradeSignal(
                    signal_type=SignalType.CLOSE_LONG,
                    timestamp=latest_time,
                    price=latest_close,
                    confidence=0.7,
                    strategy_id=self.strategy_id,
                    strategy_name=self.name,
                    metadata={'reason': 'momentum_fading'}
                )
            
            if current_position.side == SignalType.SHORT and latest_rsi < 40:
                return TradeSignal(
                    signal_type=SignalType.CLOSE_SHORT,
                    timestamp=latest_time,
                    price=latest_close,
                    confidence=0.7,
                    strategy_id=self.strategy_id,
                    strategy_name=self.name,
                    metadata={'reason': 'momentum_fading'}
                )
        
        return TradeSignal(
            signal_type=SignalType.HOLD,
            timestamp=latest_time,
            price=latest_close,
            confidence=0.5,
            strategy_id=self.strategy_id,
            strategy_name=self.name,
            metadata={'reason': 'no_clear_signal'}
        )
    
    def calculate_position_size(self, 
                               signal: TradeSignal,
                               account_balance: float,
                               risk_per_trade: float = 0.02,
                               volatility: float = 0.0) -> float:
        """Calculate position size using fixed fractional risk."""
        if volatility <= 0:
            volatility = 0.02  # Default 2% volatility
        
        risk_amount = account_balance * risk_per_trade
        stop_distance = signal.price * volatility * 2
        
        if stop_distance <= 0:
            return 0
        
        position_size = risk_amount / stop_distance
        return max(0, position_size)


class MeanReversionStrategy(BaseStrategy):
    """
    Example implementation: Mean reversion strategy.
    Trades when price deviates significantly from moving average.
    """
    
    def __init__(self, 
                 strategy_id: str = "mean_rev_001",
                 name: str = "Bollinger Mean Reversion",
                 description: str = "Trades bounces off Bollinger Bands",
                 timeframe: Timeframe = Timeframe.HOUR_1,
                 symbols: List[str] = None,
                 parameters: Dict[str, Any] = None):
        
        default_params = {
            'bb_period': 20,
            'bb_std': 2.0,
            'zscore_threshold': 2.0,
            'exit_zscore': 0.5
        }
        
        super().__init__(
            strategy_id=strategy_id,
            name=name,
            description=description,
            timeframe=timeframe,
            symbols=symbols,
            parameters={**default_params, **(parameters or {})}
        )
        
        self.required_parameters = ['bb_period', 'bb_std', 'zscore_threshold']
    
    def generate_signal(self, 
                       data: pd.DataFrame,
                       features: Dict[str, pd.Series],
                       regime: str,
                       current_position: Optional[Position] = None) -> Optional[TradeSignal]:
        
        if not self.is_active or len(data) < 2:
            return None
        
        # Only trade in sideways or low volatility regimes
        if regime in ['bull', 'volatile']:
            return None
        
        latest_close = data['close'].iloc[-1]
        latest_time = data.index[-1]
        
        zscore = features.get('zscore')
        if zscore is None:
            return None
        
        latest_zscore = zscore.iloc[-1] if hasattr(zscore, 'iloc') else zscore[-1]
        
        # Long signal: price below lower band (negative z-score)
        if latest_zscore < -self.parameters['zscore_threshold']:
            return TradeSignal(
                signal_type=SignalType.LONG,
                timestamp=latest_time,
                price=latest_close,
                confidence=min(0.9, abs(latest_zscore) / 4),
                strategy_id=self.strategy_id,
                strategy_name=self.name,
                metadata={'zscore': latest_zscore, 'regime': regime}
            )
        
        # Short signal: price above upper band (positive z-score)
        elif latest_zscore > self.parameters['zscore_threshold']:
            return TradeSignal(
                signal_type=SignalType.SHORT,
                timestamp=latest_time,
                price=latest_close,
                confidence=min(0.9, abs(latest_zscore) / 4),
                strategy_id=self.strategy_id,
                strategy_name=self.name,
                metadata={'zscore': latest_zscore, 'regime': regime}
            )
        
        # Exit signals
        if current_position:
            if current_position.side == SignalType.LONG and latest_zscore > -self.parameters['exit_zscore']:
                return TradeSignal(
                    signal_type=SignalType.CLOSE_LONG,
                    timestamp=latest_time,
                    price=latest_close,
                    confidence=0.8,
                    strategy_id=self.strategy_id,
                    strategy_name=self.name,
                    metadata={'reason': 'mean_reached', 'zscore': latest_zscore}
                )
            
            if current_position.side == SignalType.SHORT and latest_zscore < self.parameters['exit_zscore']:
                return TradeSignal(
                    signal_type=SignalType.CLOSE_SHORT,
                    timestamp=latest_time,
                    price=latest_close,
                    confidence=0.8,
                    strategy_id=self.strategy_id,
                    strategy_name=self.name,
                    metadata={'reason': 'mean_reached', 'zscore': latest_zscore}
                )
        
        return TradeSignal(
            signal_type=SignalType.HOLD,
            timestamp=latest_time,
            price=latest_close,
            confidence=0.5,
            strategy_id=self.strategy_id,
            strategy_name=self.name,
            metadata={'reason': 'no_clear_signal'}
        )
    
    def calculate_position_size(self, 
                               signal: TradeSignal,
                               account_balance: float,
                               risk_per_trade: float = 0.02,
                               volatility: float = 0.0) -> float:
        """Calculate position size inversely proportional to z-score magnitude."""
        zscore_magnitude = abs(signal.metadata.get('zscore', 2.0))
        base_size = (account_balance * risk_per_trade) / (signal.price * 0.02)
        
        # Increase size for stronger mean reversion signals
        multiplier = min(2.0, zscore_magnitude / 2)
        return base_size * multiplier
